spring:
  datasource:
    # h2-console 에서 jdbc:h2:~/testdb 로 최초 생성해주어야 한다.
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
#    properties:
#      hibernate:
#        show_sql: true  # SQL 문 출력
#        format_sql: true  # 출력된 SQL 문 포맷팅
